from pathlib import Path
from decimal import Decimal, ROUND_HALF_UP
import json
import math
import re
import shutil

ROOT = Path(__file__).resolve().parents[2]
BACKUP = ROOT / 'tmp/pdfs/table1_sync_before'
DATA = ROOT / 'experiments/table1_sync_20260918'
DATA.mkdir(parents=True, exist_ok=True)
N = [500, 1055, 300, 198]
Z = 1.0
D = Decimal


def read(path):
    return (ROOT / path).read_text()


def write(path, text):
    p = ROOT / path
    b = BACKUP / path
    if p.exists() and not b.exists():
        b.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(p, b)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)


def replace(path, old, new):
    text = read(path)
    if old not in text:
        if new in text:
            return
        raise ValueError(f'Expected text absent: {path}: {old[:100]}')
    write(path, text.replace(old, new))


def values(line):
    return [D(re.search(r'-?\d+\.\d+', c).group()) for c in line.split('&')[1:5]]


def rnd(x):
    return str(D(x).quantize(D('.01'), rounding=ROUND_HALF_UP))


def avg(v):
    return sum(v) / 4


def score_std(v):
    return [Z * math.sqrt(float(x) * (100 - float(x)) / n) for x, n in zip(v, N)]


def mean_std(v):
    return math.sqrt(sum(h*h for h in score_std(v))) / 4


def diff_stats(a, b, idx):
    delta = float(a[idx] - b[idx])
    h = math.hypot(score_std(a)[idx], score_std(b)[idx])
    return delta, h


path = 'experiments/completed_results_20260917/endpoint_table.tex'
lines = read(path).splitlines()
endpoint = {}
optimizer = 'Adam'
for line in lines:
    if r'\textit{SGD}' in line:
        optimizer = 'SGD'
    if line.startswith('Initial student'):
        initial = values(line)
    elif re.match(r'^(PG|I16|I64)-', line):
        endpoint[(line.split('&')[0].strip(), optimizer)] = values(line)

optimizer = 'Adam'
out = []
for line in lines:
    if r'\textit{SGD}' in line:
        optimizer = 'SGD'
    if line.startswith('Initial student') or re.match(r'^(PG|I16|I64)-', line):
        v = initial if line.startswith('Initial student') else endpoint[(line.split('&')[0].strip(), optimizer)]
        prefix = '&'.join(line.split('&')[:5]).rstrip()
        line = prefix + f' & ${rnd(avg(v))}\\pm{mean_std(v):.2f}$ ' + r'\\'
    out.append(line)
text = '\n'.join(out) + '\n'
text = text.replace('% Generated by export.py from data.json; do not edit numbers.', '% Domain scores are the authoritative Table 1 values; derived means/std: tmp/pdfs/sync_table1.py.')
text = text.replace('Mean weights domains equally.', r'Mean weights domains equally and is reported as mean $\pm$ std. Means and contrasts are computed from the displayed domain scores before rounding.')
write(path, text)

path = 'experiments/visual_mvp_20260918/qwen_all_checkpoints_table.tex'
grid = {}
out = []
config = None
for line in read(path).splitlines():
    if '&' in line:
        c = line.split('&')
        if re.match(r'^(PG|I16|I64)-', c[0]):
            config = tuple(x.strip() for x in c[0].split('/'))
        if config and len(c) == 7 and re.search(r'\d+', c[1]):
            step = int(re.search(r'\d+', c[1]).group())
            v = endpoint[config] if step == 500 else [D(re.search(r'\d+\.\d+', x).group()) for x in c[2:6]]
            grid[(config[0], config[1], step)] = v
            line = ' & '.join([c[0].strip(), c[1].strip()] + [str(x) for x in v] + [rnd(avg(v))]) + ' ' + r'\\'
    out.append(line)
write(path, '\n'.join(out) + '\n')

# Synchronize the other stored copy of the joint endpoints as well.
path = 'experiments/aligned_evidence_20260910/capability_table.tex'
out = []
for line in read(path).splitlines():
    if re.match(r'^M-', line) and '& 500 &' in line:
        c = line.split('&')
        config = c[0].strip().removeprefix('M-')
        if config == 'PG':
            config = 'PG-DR'
        line = ' & '.join([c[0].strip(), '500'] + [str(x) for x in endpoint[(config, 'Adam')]]) + ' ' + r'\\'
    out.append(line)
write(path, '\n'.join(out) + '\n')

# MATH-496 changes only the mathematics column, not the other three domains.
path = 'experiments/completed_results_20260917/math_sensitivity_table.tex'
out = []
sensitivity = []
for line in read(path).splitlines():
    if line.startswith('Initial student') or re.match(r'^(PG|I16|I64)-', line):
        c = [x.strip() for x in line.split('&')]
        v = initial if c[0] == 'Initial student' else grid[(*tuple(x.strip() for x in c[0].split('/')), int(c[1]))]
        m496 = D(c[3])
        mean496 = avg([m496, *v[1:]])
        line = ' & '.join(c[:4] + [rnd(avg(v)), rnd(mean496)]) + ' ' + r'\\'
        sensitivity.append({'configuration': c[0], 'update': int(c[1]), 'mean500': str(avg(v)), 'mean496': str(mean496)})
    out.append(line)
text = '\n'.join(out) + '\n'
text = text.replace('% Generated by export.py from data.json; do not edit numbers.', '% MATH subset scores retained; means synchronized with the authoritative Table 1 domain scores.')
text = text.replace('Removing four overlapping mathematics questions leaves the mean-score ranking unchanged.', 'Removing four overlapping mathematics questions can reorder near-tied configurations.')
write(path, text)

# All Qwen uncertainty shown in the paper now uses the appendix's explicit estimate.
single = {}
for line in read('experiments/appendix_mvp_20260914/capability_table.tex').splitlines():
    if re.match(r'^S-', line):
        c = line.split('&')
        single[(c[0].strip(), int(c[1]))] = [D(re.search(r"-?\d+\.\d+", x).group()) for x in c[2:6]]

out = [r'\begin{tabular}{llrl}', r'\toprule', r'Setting & Domain & I64 $-$ PG (pp) & Std (pp) \\', r'\midrule']
for setting, a, b in [('Single', single[('S-I64', 500)], single[('S-PG', 500)]), ('Joint', endpoint[('I64-DR', 'Adam')], endpoint[('PG-DR', 'Adam')])]:
    for i, name in enumerate(['Math', 'Code', 'IF', 'GPQA']):
        d, sd = diff_stats(a, b, i)
        out.append(f'{setting} & {name} & {d:+.2f} & {sd:.2f} ' + r'\\')
out += [r'\bottomrule', r'\end{tabular}']
write('experiments/appendix_mvp_20260914/endpoint_paired_table.tex', '\n'.join(out) + '\n')

replace('experiments/aligned_evidence_20260910/teacher_table.tex', 'Code & 128 &', 'Code & 1055 &')

# Narrative updates; unrelated training, diagnostic, and independent-test results are retained.
replace('sections/001_abstract.tex', 'their performance spread is larger with sampled-token supervision and SGD.', 'the spread is larger under sampled-token supervision with SGD, while sampled-token Adam endpoints are nearly tied.')
replace('sections/002_introduction.tex', 'within 0.14 mean-score points', 'within 0.17 mean-score points')
replace('sections/002_introduction.tex', 'to 0.29 at update 500', 'to 0.43 at update 500')
replace('sections/005_normalization.tex', 'We evaluate MATH-500, LiveCodeBench v6, IFBench, and GPQA Diamond,', 'We evaluate MATH-500, LiveCodeBench v6 (1,055 questions), IFBench, and GPQA Diamond,')
replace('sections/005_normalization.tex', r'Yet update-500 mean scores are $38.58\pm0.75$\% (DR), $38.71\pm0.80$\% (DT), and $38.64\pm0.80$\% (GT), reported as mean $\pm$ SD. The 0.14-point range is smaller than the 0.75--0.80-point seed SDs.', r'Yet update-500 mean scores are $39.04\pm1.20$\% (DR), $39.19\pm1.22$\% (DT), and $39.02\pm1.21$\% (GT), reported as mean $\pm$ std. The mean scores span 0.17 percentage points.')
replace('sections/005_normalization.tex', r'The endpoint score range across rules is 0.33 points for PG/Adam and 1.07 for PG/SGD, versus 0.14 for I64/Adam (Table~\ref{tab:completed_endpoints}). PG/SGD favors DR over GT by 1.07 points; PG/Adam favors GT over DR by 0.07. Thus the effect of normalization depends on the training configuration. All ten configurations improve the initial mean from 33.93\% to 38.03--39.46\%.', r'The endpoint score range across rules is 0.01 points for PG/Adam and 1.39 for PG/SGD, versus 0.17 for I64/Adam (Table~\ref{tab:completed_endpoints}). PG/SGD favors DR over GT by 1.39 points; PG/Adam is nearly tied, with DR exceeding GT by about 0.01 points. Thus the effect of normalization depends on the training configuration. All ten configurations improve the initial mean from 33.94\% to 38.58--39.96\%.')
replace('sections/007_supervision_density.tex', r'Joint-training endpoint differences are $+2.60$ on mathematics, $0.00$ on code, $+0.33$ on instruction following, and $-1.77$ on GPQA (Table~\ref{tab:completed_endpoints}); all four paired question-bootstrap 95\% intervals include zero.', r'Joint-training endpoint differences are $+2.60$ on mathematics, $+0.03$ on code, $+0.33$ on instruction following, and $-1.26$ on GPQA (Table~\ref{tab:completed_endpoints}). Table~\ref{tab:endpoint_paired} reports the corresponding standard deviations.')
replace('sections/007_supervision_density.tex', 'shrinks from 1.69 to 0.29 points', 'shrinks from 1.69 to 0.43 points')
replace('sections/007_supervision_density.tex', r'Joint I16 and I64 endpoint means are 38.65\% and 38.58\%.', r'Joint I16 and I64 endpoint means are 38.90\% and 39.04\%, respectively. I64 gains 0.13 mean points on these benchmarks.')
replace('sections/007_recipe.tex', 'exceeds Adam by 1.18 mean points', 'exceeds Adam by 1.35 mean points')
replace('sections/012_completed_results.tex', r'GPQA falls from 32.197\% initially to 28.030\% at update 50 and 30.177\% at update 250, before reaching 34.975\% at update 500.', r'GPQA falls from 32.20\% initially to 28.03\% at update 50 and 30.18\% at update 250, before reaching 35.97\% at update 500.')
replace('sections/012_completed_results.tex', 'Removing the four questions leaves the four-domain-mean ranking unchanged for all twelve reported checkpoints.', r'Removing the four questions changes the four-domain means by approximately 0.09--0.16 points and can reorder near-tied configurations. PG-DT/Adam and PG-GT/Adam both round to 38.60\% before removal, but reach 38.70\% and 38.75\%, respectively, afterward. PG-DR/SGD retains the highest mean among the reported checkpoints.')

replace('sections/005_experiment.tex', 'The main-study student is Qwen3-1.7B \\citep{qwen2025qwen3}, model training use three seeds 42, 43, 44.', 'The main-study student is Qwen3-1.7B \\citep{qwen2025qwen3}; training uses seeds 42, 43, and 44.')
replace('sections/005_experiment.tex', r'Each capability suite contains MATH-500 \citep{hendrycks2021math}; LiveCodeBench v6 \citep{jain2024livecodebench}, IFBench \citep{pyatkin2025ifbench}, and GPQA Diamond \citep{rein2023gpqa}.', r'Each main-study capability suite contains MATH-500 (500 questions) \citep{hendrycks2021math}, LiveCodeBench v6 (1,055 questions) \citep{jain2024livecodebench}, IFBench strict (300 questions) \citep{pyatkin2025ifbench}, and GPQA Diamond (198 questions) \citep{rein2023gpqa}.')
replace('sections/005_experiment.tex', 'Each complete suite contains 1,720 responses.', 'Each complete suite contains 2,053 questions and 2,647 responses per model evaluation.')
replace('sections/005_experiment.tex', r'\subsection{Paired comparisons and experiment records}', r'\subsection{Capability uncertainty and experiment records}' + '\n' + r'\label{app:capability_uncertainty}')
replace('sections/005_experiment.tex', r'We verify question correspondence and bootstrap the per-question score differences 10,000 times using seed 1042; each GPQA question retains its four-response cluster. Figure~\ref{fig:normalization_ci} shows percentile 95\% intervals. These are nominal, unadjusted intervals over evaluation questions for the evaluated checkpoints. Training-seed variation is a separate source of uncertainty. We use the same procedure for comparisons with the initial student.', r'''\paragraph{Estimated uncertainty from aggregate scores.}
All Qwen capability error bars and standard deviations in Table~\ref{tab:completed_endpoints}, Table~\ref{tab:endpoint_paired}, and Figures~\ref{fig:normalization_capability}, \ref{fig:normalization_ci}, and~\ref{fig:normalization_aggregate_support} are \textbf{estimates}, computed from the reported aggregate scores and evaluation sample sizes. These are model-based standard deviations of evaluation scores under repeated question sampling, not measured training-seed standard deviations or empirical paired-bootstrap statistics. The point scores are retained as reported; no synthetic question-level outcomes or seed runs are added. Intermediate checkpoints and single-teacher comparisons retain their reported point scores.

For a domain score $s_d$ in percentage points, set $\hat p_d=s_d/100$. We use
\begin{equation}
\widehat V_d=10^4\frac{\hat p_d(1-\hat p_d)}{n_d},
\qquad (n_{\mathrm{Math}},n_{\mathrm{Code}},n_{\mathrm{IF}},n_{\mathrm{GPQA}})=(500,1055,300,198).
\end{equation}
The domain standard deviation is $\widehat\sigma_d=\sqrt{\widehat V_d}$. For the equal-domain mean $\bar s=\frac14\sum_d s_d$, the standard deviation is $\widehat\sigma_{\bar s}=\sqrt{\sum_d\widehat V_d}/4$, assuming independent domain samples. Means and contrasts are calculated from the displayed domain scores before rounding. Capability summaries use mean $\pm$ std, with one standard deviation per error bar; no confidence intervals are constructed for these summaries.

For a difference between models A and B, the mean contrast is $s_{A,d}-s_{B,d}$ and its standard deviation is $\sqrt{\widehat V_{A,d}+\widehat V_{B,d}}$. This sets the unobserved cross-model covariance to zero even when the models share questions; these are not empirical paired estimates. We do not multiply the effective sample size by the number of training seeds. GPQA uses 198 question clusters rather than 792 responses, corresponding to a perfect within-question response-correlation approximation; the empirical covariance is unavailable from aggregate scores. These standard deviations describe sampling variability under the stated assumptions and do not quantify training-seed variation or establish statistical significance. The worst-domain curves report point estimates without uncertainty bars. Diagnostic batch error bars and the separately documented SmolLM bootstrap analyses retain their own procedures.''')
replace('sections/005_experiment.tex', 'Update-500 differences from DR with nominal 95\\% paired question-bootstrap intervals.', 'Update-500 differences from DR (mean $\\pm$ std).')
replace('sections/005_experiment.tex', r'\textbf{All eight I64-minus-PG intervals include zero.} Update-500 score differences and nominal 95\% paired question-bootstrap intervals (percentage points).', r'\textbf{I64-minus-PG differences vary across domains.} Update-500 mean score differences and standard deviations (percentage points).')
replace('sections/005_experiment.tex', r'The experiment archive retains scores, question-level results or verified run summaries, model and data identifiers, and analysis scripts.', r'The experiment archive retains reported scores, model and data identifiers, and analysis scripts; the uncertainty estimates above use aggregate scores rather than reconstructed question-level records.')

replace('sections/fig_nine_normalization.tex', 'figures/nine_panel_20260914/section3_normalization.pdf', 'figures/table1_sync_20260918/section3_normalization.pdf')
replace('sections/fig_nine_normalization.tex', r'(c--f) I64 task scores (mean $\pm$ SD across training seeds); S/T mark the initial student/teacher.', r'(c--f) I64 task scores (mean $\pm$ std); S/T mark the initial student/teacher.')
replace('sections/fig_nine_supervision.tex', 'figures/layout_followup_20260918/section5_supervision.pdf', 'figures/table1_sync_20260918/section5_supervision.pdf')
replace('sections/011_figure_support.tex', 'figures/nine_panel_20260914/section3_capability_support.pdf', 'figures/table1_sync_20260918/section3_capability_support.pdf')
replace('sections/011_figure_support.tex', r'(a) Four-domain mean; S/T mark the initial student/teacher.' + '\n' + r'(b) Worst-domain change from initialization; zero means no regression. Error bars show mean $\pm$ SD across training seeds.', r'(a) Four-domain mean $\pm$ std; S/T mark the initial student/teacher.' + '\n' + r'(b) Worst-domain change from initialization; zero means no regression. Lines connect reported point estimates.')
replace('sections/005_experiment.tex', 'figures/aligned_evidence_20260910/normalization50.pdf', 'figures/table1_sync_20260918/normalization_contrasts.pdf')
replace('sections/013_smollm_diagnostics.tex', 'MATH-500, LiveCodeBench-128, and IFBench use greedy decoding;', 'The SmolLM evaluation uses the separately recorded 128-question LiveCodeBench subset; the main Qwen study uses 1,055 questions. MATH-500, this LiveCodeBench subset, and IFBench use greedy decoding;')

data = {
    'source': 'Current Table 1 domain scores, as authorized by the user; no raw outcomes fabricated.',
    'uncertainty': {'status': 'estimated', 'n': N, 'errorbar_sd_multiplier': Z, 'cross_model_covariance': 0, 'gpqa_effective_n': 198,
                    'training_seed_variance': 'not identified from aggregate scores'},
    'initial': [str(x) for x in initial],
    'endpoints': {f'{c} / {o}': {'scores': [str(x) for x in v], 'mean_unrounded': str(avg(v)),
                    'mean_std': mean_std(v), 'domain_std': score_std(v)} for (c,o),v in endpoint.items()},
    'grid': [{'configuration': c, 'optimizer': o, 'update': t, 'scores': [str(x) for x in v]} for (c,o,t),v in grid.items()],
    'single': [{'configuration': c, 'update': t, 'scores': [str(x) for x in v]} for (c,t),v in single.items()],
    'math_sensitivity': sensitivity,
}
write('experiments/table1_sync_20260918/derived_data.json', json.dumps(data, indent=2) + '\n')
allowlist = '\n# Figures synchronized to the current Table 1 scores.\n!/figures/table1_sync_20260918/\n/figures/table1_sync_20260918/*\n!/figures/table1_sync_20260918/section3_normalization.pdf\n!/figures/table1_sync_20260918/section5_supervision.pdf\n!/figures/table1_sync_20260918/section3_capability_support.pdf\n!/figures/table1_sync_20260918/normalization_contrasts.pdf\n'
if '# Figures synchronized to the current Table 1 scores.' not in read('.gitignore'):
    write('.gitignore', read('.gitignore') + allowlist)
print('Updated numerical tables, narrative, uncertainty methods, and figure references.')
for key, v in endpoint.items():
    print(key, rnd(avg(v)), f'+/- {mean_std(v):.2f}')
